/* tslint:disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: Record<string, never>;
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    departments: Department;
    services: Service;
    'execution-mappings': ExecutionMapping;
    categories: Category;
    applications: Application;
    'service-views': ServiceView;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    departments: {
      services: 'services';
    };
    categories: {
      services: 'services';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'execution-mappings':
      | ExecutionMappingsSelect<false>
      | ExecutionMappingsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'service-views': ServiceViewsSelect<false> | ServiceViewsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions':
      | FormSubmissionsSelect<false>
      | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    'payload-preferences':
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    'payload-migrations':
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: Record<string, never>;
  globalsSelect: Record<string, never>;
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'agent')[] | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * e.g., https://mfa.gov.mg
   */
  baseUrl: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  auth?: {
    /**
     * The URL to generate the token
     */
    tokenURL?: string | null;
    clientId?: string | null;
    clientSecret?: string | null;
    scope?: string | null;
  };
  retries?: {
    max?: number | null;
    timeout?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name if not provided)
   */
  slug: string;
  description?: string | null;
  services?: {
    docs?: (number | Service)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Identifiant unique. Convention : MINISTRY-DOMAIN-NNN (ex : MID-AUTH-001)
   */
  serviceId: string;
  slug: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ex : autorisation, attestation, enregistrement
   */
  type?: string | null;
  status: 'active' | 'draft' | 'deprecated' | 'unknown';
  /**
   * URL canonique de la page officielle de la procédure
   */
  url?: string | null;
  owner: {
    /**
     * Code court ou nom complet (ex : MID, Ministère de l'Intérieur)
     */
    ministry: string;
    /**
     * Entité autonome sous tutelle du ministère (ex : Office du Tourisme)
     */
    entity?: string | null;
    directorate?: string | null;
    serviceUnit?: string | null;
  };
  category?: (number | null) | Category;
  /**
   * Laisser vide pour une procédure d'application nationale
   */
  department?: (number | null) | Department;
  /**
   * Ex : Particuliers, Entreprises, Associations
   */
  audience?: string | null;
  eligibility?: string | null;
  languages?:
    | {
        /**
         * Ex : fr, mg, en
         */
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  access?: {
    channel?: ('online' | 'offline' | 'hybrid' | 'unknown') | null;
    submissionPoints?:
      | {
          /**
           * Ex : Commune de résidence, portail.gov.mg
           */
          point?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  processingTime?: {
    /**
     * Délai réglementaire ou déclaré en jours ouvrables
     */
    slaDays?: number | null;
    /**
     * Texte exact tel qu'extrait (ex : 15 jours ouvrables à compter de la réception du dossier complet)
     */
    rawText?: string | null;
  };
  documentsRequired?:
    | {
        /**
         * Code issu du dictionnaire de taxonomie
         */
        documentTypeCode:
          | 'DOC_ID_CIN'
          | 'DOC_CIV_BIRTH'
          | 'DOC_RES_CERT'
          | 'DOC_SUP_ENVELOPE_A3'
          | 'DOC_SUP_STAMP'
          | 'DOC_SUP_FOLDING_FILE'
          | 'DOC_REQ_APPLICATION_LETTER'
          | 'DOC_REQ_APPLICATION_FORM'
          | 'DOC_PAY_BANK_SLIP'
          | 'DOC_PAY_INVOICE'
          | 'DOC_ID_PASSPORT'
          | 'DOC_VEH_REG_CARD'
          | 'DOC_EDU_TRANSCRIPT'
          | 'DOC_EDU_CERT_SUCCESS'
          | 'DOC_EDU_RESEARCH_MEMOIR'
          | 'DOC_HEALTH_MED_FORM'
          | 'DOC_TECH_ANALYSIS_REPORT'
          | 'DOC_AUTH_INTRO_LETTER'
          | 'DOC_ID_PHOTO';
        label: string;
        requirementLevel: 'required' | 'conditional' | 'optional';
        /**
         * Renseigner uniquement si conditionnel (ex : Pour les demandeurs étrangers)
         */
        condition?: string | null;
        id?: string | null;
      }[]
    | null;
  fee?: {
    currency?: 'MGA' | null;
    model?:
      | (
          | 'fixed'
          | 'conditional'
          | 'range'
          | 'composite'
          | 'percentage'
          | 'unknown'
        )
      | null;
    rules?:
      | {
          /**
           * Pattern : rule_xxx (ex : rule_fixed_base)
           */
          ruleId: string;
          type: 'fixed' | 'range' | 'percentage' | 'component' | 'unknown';
          amount?: number | null;
          minAmount?: number | null;
          maxAmount?: number | null;
          percentage?: number | null;
          condition?: string | null;
          appliesTo?: string | null;
          componentLabel?: string | null;
          id?: string | null;
        }[]
      | null;
    summary?: {
      isConditional?: boolean | null;
      minAmount?: number | null;
      maxAmount?: number | null;
      defaultAmount?: number | null;
      /**
       * Doit correspondre au nombre d'entrées dans Règles tarifaires (BR-005)
       */
      ruleCount?: number | null;
    };
  };
  workflow?: {
    normalizationConfidence?:
      | ('auto_high' | 'auto_medium' | 'manual_required')
      | null;
    reviewStatus?:
      | ('approved_auto' | 'review_required' | 'manual_required')
      | null;
    steps?:
      | {
          /**
           * Pattern : step_xxx (ex : step_depot_dossier)
           */
          stepId: string;
          order: number;
          label: string;
          description?: string | null;
          stepType:
            | 'submission'
            | 'verification'
            | 'inspection'
            | 'payment'
            | 'instruction'
            | 'approval'
            | 'decision'
            | 'notification'
            | 'delivery'
            | 'archival'
            | 'other';
          actor?:
            | ('citizen' | 'business' | 'administration' | 'mixed' | 'unknown')
            | null;
          channel?: ('offline' | 'online' | 'hybrid' | 'unknown') | null;
          requiresPayment?: boolean | null;
          slaDays?: number | null;
          documentsIn?:
            | {
                documentTypeCode?:
                  | (
                      | 'DOC_ID_CIN'
                      | 'DOC_CIV_BIRTH'
                      | 'DOC_RES_CERT'
                      | 'DOC_SUP_ENVELOPE_A3'
                      | 'DOC_SUP_STAMP'
                      | 'DOC_SUP_FOLDING_FILE'
                      | 'DOC_REQ_APPLICATION_LETTER'
                      | 'DOC_REQ_APPLICATION_FORM'
                      | 'DOC_PAY_BANK_SLIP'
                      | 'DOC_PAY_INVOICE'
                      | 'DOC_ID_PASSPORT'
                      | 'DOC_VEH_REG_CARD'
                      | 'DOC_EDU_TRANSCRIPT'
                      | 'DOC_EDU_CERT_SUCCESS'
                      | 'DOC_EDU_RESEARCH_MEMOIR'
                      | 'DOC_HEALTH_MED_FORM'
                      | 'DOC_TECH_ANALYSIS_REPORT'
                      | 'DOC_AUTH_INTRO_LETTER'
                      | 'DOC_ID_PHOTO'
                    )
                  | null;
                id?: string | null;
              }[]
            | null;
          documentsOut?:
            | {
                documentTypeCode?:
                  | (
                      | 'DOC_ID_CIN'
                      | 'DOC_CIV_BIRTH'
                      | 'DOC_RES_CERT'
                      | 'DOC_SUP_ENVELOPE_A3'
                      | 'DOC_SUP_STAMP'
                      | 'DOC_SUP_FOLDING_FILE'
                      | 'DOC_REQ_APPLICATION_LETTER'
                      | 'DOC_REQ_APPLICATION_FORM'
                      | 'DOC_PAY_BANK_SLIP'
                      | 'DOC_PAY_INVOICE'
                      | 'DOC_ID_PASSPORT'
                      | 'DOC_VEH_REG_CARD'
                      | 'DOC_EDU_TRANSCRIPT'
                      | 'DOC_EDU_CERT_SUCCESS'
                      | 'DOC_EDU_RESEARCH_MEMOIR'
                      | 'DOC_HEALTH_MED_FORM'
                      | 'DOC_TECH_ANALYSIS_REPORT'
                      | 'DOC_AUTH_INTRO_LETTER'
                      | 'DOC_ID_PHOTO'
                    )
                  | null;
                id?: string | null;
              }[]
            | null;
          responsibleUnit?: string | null;
          confidence?: ('auto_high' | 'auto_medium' | 'manual_required') | null;
          id?: string | null;
        }[]
      | null;
  };
  supportContact?: {
    phone?: string | null;
    email?: string | null;
    officeAddress?: string | null;
  };
  /**
   * Super admins can see all forms; others see forms from their tenant.
   */
  form?: (number | null) | Form;
  /**
   * Champs calculés par le pipeline de normalisation — ne pas modifier manuellement
   */
  metrics?: {
    frictionScore?: number | null;
    documentsCount?: number | null;
    /**
     * Valeur entre 0.0 et 1.0
     */
    manualRequiredShare?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Used for URL paths, example: /category-slug
   */
  slug: string;
  description?: string | null;
  /**
   * Icon name from a predefined set, e.g., "education", "health"
   */
  icon?: string | null;
  /**
   * Color class for category cards, e.g., blue, red
   */
  color?: string | null;
  services?: {
    docs?: (number | Service)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            /**
             * Identifiant stable (snake_case). Auto-généré depuis name si vide.
             */
            fieldId?: string | null;
            /**
             * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
             */
            mapsToDocumentTypeCode?:
              | (
                  | 'DOC_ID_CIN'
                  | 'DOC_CIV_BIRTH'
                  | 'DOC_RES_CERT'
                  | 'DOC_SUP_ENVELOPE_A3'
                  | 'DOC_SUP_STAMP'
                  | 'DOC_SUP_FOLDING_FILE'
                  | 'DOC_REQ_APPLICATION_LETTER'
                  | 'DOC_REQ_APPLICATION_FORM'
                  | 'DOC_PAY_BANK_SLIP'
                  | 'DOC_PAY_INVOICE'
                  | 'DOC_ID_PASSPORT'
                  | 'DOC_VEH_REG_CARD'
                  | 'DOC_EDU_TRANSCRIPT'
                  | 'DOC_EDU_CERT_SUCCESS'
                  | 'DOC_EDU_RESEARCH_MEMOIR'
                  | 'DOC_HEALTH_MED_FORM'
                  | 'DOC_TECH_ANALYSIS_REPORT'
                  | 'DOC_AUTH_INTRO_LETTER'
                  | 'DOC_ID_PHOTO'
                )
              | null;
            /**
             * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
             */
            mapsToWorkflowStepId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            /**
             * Identifiant stable (snake_case). Auto-généré depuis name si vide.
             */
            fieldId?: string | null;
            /**
             * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
             */
            mapsToDocumentTypeCode?:
              | (
                  | 'DOC_ID_CIN'
                  | 'DOC_CIV_BIRTH'
                  | 'DOC_RES_CERT'
                  | 'DOC_SUP_ENVELOPE_A3'
                  | 'DOC_SUP_STAMP'
                  | 'DOC_SUP_FOLDING_FILE'
                  | 'DOC_REQ_APPLICATION_LETTER'
                  | 'DOC_REQ_APPLICATION_FORM'
                  | 'DOC_PAY_BANK_SLIP'
                  | 'DOC_PAY_INVOICE'
                  | 'DOC_ID_PASSPORT'
                  | 'DOC_VEH_REG_CARD'
                  | 'DOC_EDU_TRANSCRIPT'
                  | 'DOC_EDU_CERT_SUCCESS'
                  | 'DOC_EDU_RESEARCH_MEMOIR'
                  | 'DOC_HEALTH_MED_FORM'
                  | 'DOC_TECH_ANALYSIS_REPORT'
                  | 'DOC_AUTH_INTRO_LETTER'
                  | 'DOC_ID_PHOTO'
                )
              | null;
            /**
             * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
             */
            mapsToWorkflowStepId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format:
                  | 'left'
                  | 'start'
                  | 'center'
                  | 'right'
                  | 'end'
                  | 'justify'
                  | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Identifiant stable (snake_case). Auto-généré depuis name si vide.
             */
            fieldId?: string | null;
            /**
             * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
             */
            mapsToDocumentTypeCode?:
              | (
                  | 'DOC_ID_CIN'
                  | 'DOC_CIV_BIRTH'
                  | 'DOC_RES_CERT'
                  | 'DOC_SUP_ENVELOPE_A3'
                  | 'DOC_SUP_STAMP'
                  | 'DOC_SUP_FOLDING_FILE'
                  | 'DOC_REQ_APPLICATION_LETTER'
                  | 'DOC_REQ_APPLICATION_FORM'
                  | 'DOC_PAY_BANK_SLIP'
                  | 'DOC_PAY_INVOICE'
                  | 'DOC_ID_PASSPORT'
                  | 'DOC_VEH_REG_CARD'
                  | 'DOC_EDU_TRANSCRIPT'
                  | 'DOC_EDU_CERT_SUCCESS'
                  | 'DOC_EDU_RESEARCH_MEMOIR'
                  | 'DOC_HEALTH_MED_FORM'
                  | 'DOC_TECH_ANALYSIS_REPORT'
                  | 'DOC_AUTH_INTRO_LETTER'
                  | 'DOC_ID_PHOTO'
                )
              | null;
            /**
             * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
             */
            mapsToWorkflowStepId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            /**
             * Identifiant stable (snake_case). Auto-généré depuis name si vide.
             */
            fieldId?: string | null;
            /**
             * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
             */
            mapsToDocumentTypeCode?:
              | (
                  | 'DOC_ID_CIN'
                  | 'DOC_CIV_BIRTH'
                  | 'DOC_RES_CERT'
                  | 'DOC_SUP_ENVELOPE_A3'
                  | 'DOC_SUP_STAMP'
                  | 'DOC_SUP_FOLDING_FILE'
                  | 'DOC_REQ_APPLICATION_LETTER'
                  | 'DOC_REQ_APPLICATION_FORM'
                  | 'DOC_PAY_BANK_SLIP'
                  | 'DOC_PAY_INVOICE'
                  | 'DOC_ID_PASSPORT'
                  | 'DOC_VEH_REG_CARD'
                  | 'DOC_EDU_TRANSCRIPT'
                  | 'DOC_EDU_CERT_SUCCESS'
                  | 'DOC_EDU_RESEARCH_MEMOIR'
                  | 'DOC_HEALTH_MED_FORM'
                  | 'DOC_TECH_ANALYSIS_REPORT'
                  | 'DOC_AUTH_INTRO_LETTER'
                  | 'DOC_ID_PHOTO'
                )
              | null;
            /**
             * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
             */
            mapsToWorkflowStepId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            /**
             * Identifiant stable (snake_case). Auto-généré depuis name si vide.
             */
            fieldId?: string | null;
            /**
             * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
             */
            mapsToDocumentTypeCode?:
              | (
                  | 'DOC_ID_CIN'
                  | 'DOC_CIV_BIRTH'
                  | 'DOC_RES_CERT'
                  | 'DOC_SUP_ENVELOPE_A3'
                  | 'DOC_SUP_STAMP'
                  | 'DOC_SUP_FOLDING_FILE'
                  | 'DOC_REQ_APPLICATION_LETTER'
                  | 'DOC_REQ_APPLICATION_FORM'
                  | 'DOC_PAY_BANK_SLIP'
                  | 'DOC_PAY_INVOICE'
                  | 'DOC_ID_PASSPORT'
                  | 'DOC_VEH_REG_CARD'
                  | 'DOC_EDU_TRANSCRIPT'
                  | 'DOC_EDU_CERT_SUCCESS'
                  | 'DOC_EDU_RESEARCH_MEMOIR'
                  | 'DOC_HEALTH_MED_FORM'
                  | 'DOC_TECH_ANALYSIS_REPORT'
                  | 'DOC_AUTH_INTRO_LETTER'
                  | 'DOC_ID_PHOTO'
                )
              | null;
            /**
             * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
             */
            mapsToWorkflowStepId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            /**
             * Identifiant stable (snake_case). Auto-généré depuis name si vide.
             */
            fieldId?: string | null;
            /**
             * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
             */
            mapsToDocumentTypeCode?:
              | (
                  | 'DOC_ID_CIN'
                  | 'DOC_CIV_BIRTH'
                  | 'DOC_RES_CERT'
                  | 'DOC_SUP_ENVELOPE_A3'
                  | 'DOC_SUP_STAMP'
                  | 'DOC_SUP_FOLDING_FILE'
                  | 'DOC_REQ_APPLICATION_LETTER'
                  | 'DOC_REQ_APPLICATION_FORM'
                  | 'DOC_PAY_BANK_SLIP'
                  | 'DOC_PAY_INVOICE'
                  | 'DOC_ID_PASSPORT'
                  | 'DOC_VEH_REG_CARD'
                  | 'DOC_EDU_TRANSCRIPT'
                  | 'DOC_EDU_CERT_SUCCESS'
                  | 'DOC_EDU_RESEARCH_MEMOIR'
                  | 'DOC_HEALTH_MED_FORM'
                  | 'DOC_TECH_ANALYSIS_REPORT'
                  | 'DOC_AUTH_INTRO_LETTER'
                  | 'DOC_ID_PHOTO'
                )
              | null;
            /**
             * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
             */
            mapsToWorkflowStepId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            /**
             * Identifiant stable (snake_case). Auto-généré depuis name si vide.
             */
            fieldId?: string | null;
            /**
             * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
             */
            mapsToDocumentTypeCode?:
              | (
                  | 'DOC_ID_CIN'
                  | 'DOC_CIV_BIRTH'
                  | 'DOC_RES_CERT'
                  | 'DOC_SUP_ENVELOPE_A3'
                  | 'DOC_SUP_STAMP'
                  | 'DOC_SUP_FOLDING_FILE'
                  | 'DOC_REQ_APPLICATION_LETTER'
                  | 'DOC_REQ_APPLICATION_FORM'
                  | 'DOC_PAY_BANK_SLIP'
                  | 'DOC_PAY_INVOICE'
                  | 'DOC_ID_PASSPORT'
                  | 'DOC_VEH_REG_CARD'
                  | 'DOC_EDU_TRANSCRIPT'
                  | 'DOC_EDU_CERT_SUCCESS'
                  | 'DOC_EDU_RESEARCH_MEMOIR'
                  | 'DOC_HEALTH_MED_FORM'
                  | 'DOC_TECH_ANALYSIS_REPORT'
                  | 'DOC_AUTH_INTRO_LETTER'
                  | 'DOC_ID_PHOTO'
                )
              | null;
            /**
             * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
             */
            mapsToWorkflowStepId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            title: string;
            description?: string | null;
            /**
             * Leave blank for no button (e.g. with Option Selector field or final step)
             */
            proceedLabel?: string | null;
            /**
             * If true, the form will allow the user to go back to the previous step from this step
             */
            allowBack?: boolean | null;
            fields?:
              | (
                  | {
                      name: string;
                      label?: string | null;
                      width?: number | null;
                      defaultValue?: string | null;
                      required?: boolean | null;
                      /**
                       * Identifiant stable (snake_case). Auto-généré depuis name si vide.
                       */
                      fieldId?: string | null;
                      /**
                       * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
                       */
                      mapsToDocumentTypeCode?:
                        | (
                            | 'DOC_ID_CIN'
                            | 'DOC_CIV_BIRTH'
                            | 'DOC_RES_CERT'
                            | 'DOC_SUP_ENVELOPE_A3'
                            | 'DOC_SUP_STAMP'
                            | 'DOC_SUP_FOLDING_FILE'
                            | 'DOC_REQ_APPLICATION_LETTER'
                            | 'DOC_REQ_APPLICATION_FORM'
                            | 'DOC_PAY_BANK_SLIP'
                            | 'DOC_PAY_INVOICE'
                            | 'DOC_ID_PASSPORT'
                            | 'DOC_VEH_REG_CARD'
                            | 'DOC_EDU_TRANSCRIPT'
                            | 'DOC_EDU_CERT_SUCCESS'
                            | 'DOC_EDU_RESEARCH_MEMOIR'
                            | 'DOC_HEALTH_MED_FORM'
                            | 'DOC_TECH_ANALYSIS_REPORT'
                            | 'DOC_AUTH_INTRO_LETTER'
                            | 'DOC_ID_PHOTO'
                          )
                        | null;
                      /**
                       * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
                       */
                      mapsToWorkflowStepId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'text';
                    }
                  | {
                      name: string;
                      label?: string | null;
                      width?: number | null;
                      defaultValue?: string | null;
                      required?: boolean | null;
                      /**
                       * Identifiant stable (snake_case). Auto-généré depuis name si vide.
                       */
                      fieldId?: string | null;
                      /**
                       * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
                       */
                      mapsToDocumentTypeCode?:
                        | (
                            | 'DOC_ID_CIN'
                            | 'DOC_CIV_BIRTH'
                            | 'DOC_RES_CERT'
                            | 'DOC_SUP_ENVELOPE_A3'
                            | 'DOC_SUP_STAMP'
                            | 'DOC_SUP_FOLDING_FILE'
                            | 'DOC_REQ_APPLICATION_LETTER'
                            | 'DOC_REQ_APPLICATION_FORM'
                            | 'DOC_PAY_BANK_SLIP'
                            | 'DOC_PAY_INVOICE'
                            | 'DOC_ID_PASSPORT'
                            | 'DOC_VEH_REG_CARD'
                            | 'DOC_EDU_TRANSCRIPT'
                            | 'DOC_EDU_CERT_SUCCESS'
                            | 'DOC_EDU_RESEARCH_MEMOIR'
                            | 'DOC_HEALTH_MED_FORM'
                            | 'DOC_TECH_ANALYSIS_REPORT'
                            | 'DOC_AUTH_INTRO_LETTER'
                            | 'DOC_ID_PHOTO'
                          )
                        | null;
                      /**
                       * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
                       */
                      mapsToWorkflowStepId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'textarea';
                    }
                  | {
                      name: string;
                      label?: string | null;
                      width?: number | null;
                      defaultValue?: string | null;
                      placeholder?: string | null;
                      options?:
                        | {
                            label: string;
                            value: string;
                            id?: string | null;
                          }[]
                        | null;
                      required?: boolean | null;
                      /**
                       * Identifiant stable (snake_case). Auto-généré depuis name si vide.
                       */
                      fieldId?: string | null;
                      /**
                       * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
                       */
                      mapsToDocumentTypeCode?:
                        | (
                            | 'DOC_ID_CIN'
                            | 'DOC_CIV_BIRTH'
                            | 'DOC_RES_CERT'
                            | 'DOC_SUP_ENVELOPE_A3'
                            | 'DOC_SUP_STAMP'
                            | 'DOC_SUP_FOLDING_FILE'
                            | 'DOC_REQ_APPLICATION_LETTER'
                            | 'DOC_REQ_APPLICATION_FORM'
                            | 'DOC_PAY_BANK_SLIP'
                            | 'DOC_PAY_INVOICE'
                            | 'DOC_ID_PASSPORT'
                            | 'DOC_VEH_REG_CARD'
                            | 'DOC_EDU_TRANSCRIPT'
                            | 'DOC_EDU_CERT_SUCCESS'
                            | 'DOC_EDU_RESEARCH_MEMOIR'
                            | 'DOC_HEALTH_MED_FORM'
                            | 'DOC_TECH_ANALYSIS_REPORT'
                            | 'DOC_AUTH_INTRO_LETTER'
                            | 'DOC_ID_PHOTO'
                          )
                        | null;
                      /**
                       * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
                       */
                      mapsToWorkflowStepId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'select';
                    }
                  | {
                      name: string;
                      label?: string | null;
                      width?: number | null;
                      required?: boolean | null;
                      /**
                       * Identifiant stable (snake_case). Auto-généré depuis name si vide.
                       */
                      fieldId?: string | null;
                      /**
                       * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
                       */
                      mapsToDocumentTypeCode?:
                        | (
                            | 'DOC_ID_CIN'
                            | 'DOC_CIV_BIRTH'
                            | 'DOC_RES_CERT'
                            | 'DOC_SUP_ENVELOPE_A3'
                            | 'DOC_SUP_STAMP'
                            | 'DOC_SUP_FOLDING_FILE'
                            | 'DOC_REQ_APPLICATION_LETTER'
                            | 'DOC_REQ_APPLICATION_FORM'
                            | 'DOC_PAY_BANK_SLIP'
                            | 'DOC_PAY_INVOICE'
                            | 'DOC_ID_PASSPORT'
                            | 'DOC_VEH_REG_CARD'
                            | 'DOC_EDU_TRANSCRIPT'
                            | 'DOC_EDU_CERT_SUCCESS'
                            | 'DOC_EDU_RESEARCH_MEMOIR'
                            | 'DOC_HEALTH_MED_FORM'
                            | 'DOC_TECH_ANALYSIS_REPORT'
                            | 'DOC_AUTH_INTRO_LETTER'
                            | 'DOC_ID_PHOTO'
                          )
                        | null;
                      /**
                       * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
                       */
                      mapsToWorkflowStepId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'email';
                    }
                  | {
                      name: string;
                      label?: string | null;
                      width?: number | null;
                      defaultValue?: number | null;
                      required?: boolean | null;
                      /**
                       * Identifiant stable (snake_case). Auto-généré depuis name si vide.
                       */
                      fieldId?: string | null;
                      /**
                       * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
                       */
                      mapsToDocumentTypeCode?:
                        | (
                            | 'DOC_ID_CIN'
                            | 'DOC_CIV_BIRTH'
                            | 'DOC_RES_CERT'
                            | 'DOC_SUP_ENVELOPE_A3'
                            | 'DOC_SUP_STAMP'
                            | 'DOC_SUP_FOLDING_FILE'
                            | 'DOC_REQ_APPLICATION_LETTER'
                            | 'DOC_REQ_APPLICATION_FORM'
                            | 'DOC_PAY_BANK_SLIP'
                            | 'DOC_PAY_INVOICE'
                            | 'DOC_ID_PASSPORT'
                            | 'DOC_VEH_REG_CARD'
                            | 'DOC_EDU_TRANSCRIPT'
                            | 'DOC_EDU_CERT_SUCCESS'
                            | 'DOC_EDU_RESEARCH_MEMOIR'
                            | 'DOC_HEALTH_MED_FORM'
                            | 'DOC_TECH_ANALYSIS_REPORT'
                            | 'DOC_AUTH_INTRO_LETTER'
                            | 'DOC_ID_PHOTO'
                          )
                        | null;
                      /**
                       * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
                       */
                      mapsToWorkflowStepId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'number';
                    }
                  | {
                      name: string;
                      label?: string | null;
                      width?: number | null;
                      required?: boolean | null;
                      defaultValue?: boolean | null;
                      /**
                       * Identifiant stable (snake_case). Auto-généré depuis name si vide.
                       */
                      fieldId?: string | null;
                      /**
                       * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
                       */
                      mapsToDocumentTypeCode?:
                        | (
                            | 'DOC_ID_CIN'
                            | 'DOC_CIV_BIRTH'
                            | 'DOC_RES_CERT'
                            | 'DOC_SUP_ENVELOPE_A3'
                            | 'DOC_SUP_STAMP'
                            | 'DOC_SUP_FOLDING_FILE'
                            | 'DOC_REQ_APPLICATION_LETTER'
                            | 'DOC_REQ_APPLICATION_FORM'
                            | 'DOC_PAY_BANK_SLIP'
                            | 'DOC_PAY_INVOICE'
                            | 'DOC_ID_PASSPORT'
                            | 'DOC_VEH_REG_CARD'
                            | 'DOC_EDU_TRANSCRIPT'
                            | 'DOC_EDU_CERT_SUCCESS'
                            | 'DOC_EDU_RESEARCH_MEMOIR'
                            | 'DOC_HEALTH_MED_FORM'
                            | 'DOC_TECH_ANALYSIS_REPORT'
                            | 'DOC_AUTH_INTRO_LETTER'
                            | 'DOC_ID_PHOTO'
                          )
                        | null;
                      /**
                       * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
                       */
                      mapsToWorkflowStepId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'checkbox';
                    }
                  | {
                      message?: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format:
                            | 'left'
                            | 'start'
                            | 'center'
                            | 'right'
                            | 'end'
                            | 'justify'
                            | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      } | null;
                      /**
                       * Identifiant stable (snake_case). Auto-généré depuis name si vide.
                       */
                      fieldId?: string | null;
                      /**
                       * Si ce champ collecte un document, sélectionner le code taxonomie correspondant.
                       */
                      mapsToDocumentTypeCode?:
                        | (
                            | 'DOC_ID_CIN'
                            | 'DOC_CIV_BIRTH'
                            | 'DOC_RES_CERT'
                            | 'DOC_SUP_ENVELOPE_A3'
                            | 'DOC_SUP_STAMP'
                            | 'DOC_SUP_FOLDING_FILE'
                            | 'DOC_REQ_APPLICATION_LETTER'
                            | 'DOC_REQ_APPLICATION_FORM'
                            | 'DOC_PAY_BANK_SLIP'
                            | 'DOC_PAY_INVOICE'
                            | 'DOC_ID_PASSPORT'
                            | 'DOC_VEH_REG_CARD'
                            | 'DOC_EDU_TRANSCRIPT'
                            | 'DOC_EDU_CERT_SUCCESS'
                            | 'DOC_EDU_RESEARCH_MEMOIR'
                            | 'DOC_HEALTH_MED_FORM'
                            | 'DOC_TECH_ANALYSIS_REPORT'
                            | 'DOC_AUTH_INTRO_LETTER'
                            | 'DOC_ID_PHOTO'
                          )
                        | null;
                      /**
                       * stepId de l'étape de workflow à laquelle ce champ appartient (ex: step_depot_dossier).
                       */
                      mapsToWorkflowStepId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'message';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'form-step';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format:
              | 'left'
              | 'start'
              | 'center'
              | 'right'
              | 'end'
              | 'justify'
              | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  schema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  version?: number | null;
  /**
   * Configure external API integration for this form submission.
   */
  externalIntegration?: {
    type?: ('rest' | 'webhook' | 'custom') | null;
    url?: string | null;
    method?: ('POST' | 'PUT' | 'PATCH') | null;
    headers?:
      | {
          key: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Map form fields to API fields. Leave empty to send all data as-is.
     */
    fieldMapping?:
      | {
          formField: string;
          apiField: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Execution specs for the workflow engine (wbb-service). Not served in Public API.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "execution-mappings".
 */
export interface ExecutionMapping {
  id: number;
  /**
   * Must match Services.serviceId (e.g. MAM-CENAM-B-P1)
   */
  serviceId: string;
  /**
   * Linked Services document
   */
  service: number | Service;
  /**
   * SemVer — bump on any structural change
   */
  version?: string | null;
  reviewStatus: 'approved' | 'review_required' | 'manual_required';
  normalizationConfidence?:
    | ('auto_high' | 'auto_medium' | 'manual_required')
    | null;
  process?: {
    /**
     * Pattern: proc_<serviceId_slug>
     */
    processId?: string | null;
    version?: string | null;
    actor?: ('citizen' | 'business' | 'administration' | 'mixed') | null;
    channel?: ('online' | 'offline' | 'hybrid') | null;
    estimatedDurationDays?: number | null;
    steps?:
      | {
          /**
           * Doit correspondre à workflow.steps[].stepId dans Services
           */
          stepId: string;
          order: number;
          label: string;
          stepType:
            | 'submission'
            | 'verification'
            | 'inspection'
            | 'payment'
            | 'instruction'
            | 'approval'
            | 'decision'
            | 'notification'
            | 'delivery'
            | 'archival'
            | 'other';
          actor?:
            | ('citizen' | 'business' | 'administration' | 'mixed' | 'unknown')
            | null;
          channel?: ('offline' | 'online' | 'hybrid' | 'unknown') | null;
          requiresPayment?: boolean | null;
          slaDays?: number | null;
          responsibleUnit?: string | null;
          /**
           * GovStack WBB mapping
           */
          wbbTaskType?:
            | ('UserTask' | 'ServiceTask' | 'Gateway' | 'Event')
            | null;
          /**
           * RBAC role in wbb-service (e.g. OFFICER, CITIZEN)
           */
          wbbAssigneeRole?: string | null;
          automatable?: boolean | null;
          confidence?: ('auto_high' | 'auto_medium' | 'manual_required') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Commentaires de l'équipe de validation
   */
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  trackingId: string;
  /**
   * Case ID from case-api (UUID)
   */
  caseId?: string | null;
  status: 'pending' | 'processing' | 'approved' | 'rejected' | 'info_required';
  submission: number | FormSubmission;
  service?: (number | null) | Service;
  applicantEmail?: string | null;
  timeline?:
    | {
        status?: string | null;
        timestamp?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks views of service detail pages (for offline services without forms)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-views".
 */
export interface ServiceView {
  id: number;
  service: number | Service;
  viewedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'services';
    value: number | Service;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'execution-mappings';
        value: number | ExecutionMapping;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'service-views';
        value: number | ServiceView;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  baseUrl?: T;
  description?: T;
  auth?:
    | T
    | {
        tokenURL?: T;
        clientId?: T;
        clientSecret?: T;
        scope?: T;
      };
  retries?:
    | T
    | {
        max?: T;
        timeout?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  description?: T;
  services?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  tenant?: T;
  serviceId?: T;
  slug?: T;
  name?: T;
  description?: T;
  type?: T;
  status?: T;
  url?: T;
  owner?:
    | T
    | {
        ministry?: T;
        entity?: T;
        directorate?: T;
        serviceUnit?: T;
      };
  category?: T;
  department?: T;
  audience?: T;
  eligibility?: T;
  languages?:
    | T
    | {
        code?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  access?:
    | T
    | {
        channel?: T;
        submissionPoints?:
          | T
          | {
              point?: T;
              id?: T;
            };
      };
  processingTime?:
    | T
    | {
        slaDays?: T;
        rawText?: T;
      };
  documentsRequired?:
    | T
    | {
        documentTypeCode?: T;
        label?: T;
        requirementLevel?: T;
        condition?: T;
        id?: T;
      };
  fee?:
    | T
    | {
        currency?: T;
        model?: T;
        rules?:
          | T
          | {
              ruleId?: T;
              type?: T;
              amount?: T;
              minAmount?: T;
              maxAmount?: T;
              percentage?: T;
              condition?: T;
              appliesTo?: T;
              componentLabel?: T;
              id?: T;
            };
        summary?:
          | T
          | {
              isConditional?: T;
              minAmount?: T;
              maxAmount?: T;
              defaultAmount?: T;
              ruleCount?: T;
            };
      };
  workflow?:
    | T
    | {
        normalizationConfidence?: T;
        reviewStatus?: T;
        steps?:
          | T
          | {
              stepId?: T;
              order?: T;
              label?: T;
              description?: T;
              stepType?: T;
              actor?: T;
              channel?: T;
              requiresPayment?: T;
              slaDays?: T;
              documentsIn?:
                | T
                | {
                    documentTypeCode?: T;
                    id?: T;
                  };
              documentsOut?:
                | T
                | {
                    documentTypeCode?: T;
                    id?: T;
                  };
              responsibleUnit?: T;
              confidence?: T;
              id?: T;
            };
      };
  supportContact?:
    | T
    | {
        phone?: T;
        email?: T;
        officeAddress?: T;
      };
  form?: T;
  metrics?:
    | T
    | {
        frictionScore?: T;
        documentsCount?: T;
        manualRequiredShare?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "execution-mappings_select".
 */
export interface ExecutionMappingsSelect<T extends boolean = true> {
  serviceId?: T;
  service?: T;
  version?: T;
  reviewStatus?: T;
  normalizationConfidence?: T;
  process?:
    | T
    | {
        processId?: T;
        version?: T;
        actor?: T;
        channel?: T;
        estimatedDurationDays?: T;
        steps?:
          | T
          | {
              stepId?: T;
              order?: T;
              label?: T;
              stepType?: T;
              actor?: T;
              channel?: T;
              requiresPayment?: T;
              slaDays?: T;
              responsibleUnit?: T;
              wbbTaskType?: T;
              wbbAssigneeRole?: T;
              automatable?: T;
              confidence?: T;
              id?: T;
            };
      };
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  color?: T;
  services?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  trackingId?: T;
  caseId?: T;
  status?: T;
  submission?: T;
  service?: T;
  applicantEmail?: T;
  timeline?:
    | T
    | {
        status?: T;
        timestamp?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-views_select".
 */
export interface ServiceViewsSelect<T extends boolean = true> {
  service?: T;
  viewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              fieldId?: T;
              mapsToDocumentTypeCode?: T;
              mapsToWorkflowStepId?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              fieldId?: T;
              mapsToDocumentTypeCode?: T;
              mapsToWorkflowStepId?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              fieldId?: T;
              mapsToDocumentTypeCode?: T;
              mapsToWorkflowStepId?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              fieldId?: T;
              mapsToDocumentTypeCode?: T;
              mapsToWorkflowStepId?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              fieldId?: T;
              mapsToDocumentTypeCode?: T;
              mapsToWorkflowStepId?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              fieldId?: T;
              mapsToDocumentTypeCode?: T;
              mapsToWorkflowStepId?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              fieldId?: T;
              mapsToDocumentTypeCode?: T;
              mapsToWorkflowStepId?: T;
              id?: T;
              blockName?: T;
            };
        'form-step'?:
          | T
          | {
              title?: T;
              description?: T;
              proceedLabel?: T;
              allowBack?: T;
              fields?:
                | T
                | {
                    text?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          width?: T;
                          defaultValue?: T;
                          required?: T;
                          fieldId?: T;
                          mapsToDocumentTypeCode?: T;
                          mapsToWorkflowStepId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    textarea?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          width?: T;
                          defaultValue?: T;
                          required?: T;
                          fieldId?: T;
                          mapsToDocumentTypeCode?: T;
                          mapsToWorkflowStepId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    select?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          width?: T;
                          defaultValue?: T;
                          placeholder?: T;
                          options?:
                            | T
                            | {
                                label?: T;
                                value?: T;
                                id?: T;
                              };
                          required?: T;
                          fieldId?: T;
                          mapsToDocumentTypeCode?: T;
                          mapsToWorkflowStepId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    email?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          width?: T;
                          required?: T;
                          fieldId?: T;
                          mapsToDocumentTypeCode?: T;
                          mapsToWorkflowStepId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    number?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          width?: T;
                          defaultValue?: T;
                          required?: T;
                          fieldId?: T;
                          mapsToDocumentTypeCode?: T;
                          mapsToWorkflowStepId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    checkbox?:
                      | T
                      | {
                          name?: T;
                          label?: T;
                          width?: T;
                          required?: T;
                          defaultValue?: T;
                          fieldId?: T;
                          mapsToDocumentTypeCode?: T;
                          mapsToWorkflowStepId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    message?:
                      | T
                      | {
                          message?: T;
                          fieldId?: T;
                          mapsToDocumentTypeCode?: T;
                          mapsToWorkflowStepId?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  schema?: T;
  version?: T;
  externalIntegration?:
    | T
    | {
        type?: T;
        url?: T;
        method?: T;
        headers?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
            };
        fieldMapping?:
          | T
          | {
              formField?: T;
              apiField?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
